name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  pre-deploy-build-test:
    name: Pre Deploy Build Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

  deploy:
    name: Deploy
    needs: pre-deploy-build-test
    runs-on: ubuntu-latest

    steps:
      - name: Connect SSH and Deploy Project
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          allenvs: true
          script_stop: true
          script: |
            cd ${{ secrets.SSH_PROJECT_FOLDER }}

            git pull

            npm i
            npm run build
            
            bash ./pm2.bash
